# Base image with spark-submit capabilities, CMSMonitoring, CMSSpark and CERN central tools
FROM registry.cern.ch/cmsmonitoring/cmsmon-spark:v0.5.0.1

# Copy source code to the image
COPY ./src /unsuspend_tool

#Give execution permissions
RUN chmod +x /unsuspend_tool/submit_suspended_rules_preparer.sh